Document: libniscsdk
Title: Debian libniscsdk Manual
Author: <insert document author here>
Abstract: This manual describes what libniscsdk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libniscsdk/libniscsdk.sgml.gz

Format: postscript
Files: /usr/share/doc/libniscsdk/libniscsdk.ps.gz

Format: text
Files: /usr/share/doc/libniscsdk/libniscsdk.text.gz

Format: HTML
Index: /usr/share/doc/libniscsdk/html/index.html
Files: /usr/share/doc/libniscsdk/html/*.html
